#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xf3be;
constexpr uint24_t FX_DATA_BYTES = 803288;

constexpr uint24_t title = 0x000000;
constexpr uint16_t titleWidth  = 128;
constexpr uint16_t titleHeight = 32;

constexpr uint24_t vitorc = 0x000204;
constexpr uint16_t vitorcWidth  = 24;
constexpr uint16_t vitorcHeight = 32;
constexpr uint8_t  vitorcFrames = 44;

constexpr uint24_t grenade_pic = 0x001288;
constexpr uint16_t grenade_pic_width  = 8;
constexpr uint16_t grenade_pic_height = 8;
constexpr uint8_t  grenade_pic_frames = 2;

constexpr uint24_t explosion_pic = 0x00129C;
constexpr uint16_t explosion_pic_width  = 16;
constexpr uint16_t explosion_pic_height = 8;
constexpr uint8_t  explosion_pic_frames = 4;

constexpr uint24_t grenade_trace = 0x0012E0;
constexpr uint16_t grenade_trace_width  = 8;
constexpr uint16_t grenade_trace_height = 8;

constexpr uint24_t shoot_pic = 0x0012EC;
constexpr uint16_t shoot_pic_width  = 8;
constexpr uint16_t shoot_pic_height = 8;

constexpr uint24_t egg_pic = 0x0012F8;
constexpr uint16_t egg_pic_width  = 8;
constexpr uint16_t egg_pic_height = 8;
constexpr uint8_t  egg_pic_frames = 2;

constexpr uint24_t cocon = 0x00130C;
constexpr uint16_t coconWidth  = 40;
constexpr uint16_t coconHeight = 64;

constexpr uint24_t rocket = 0x001450;
constexpr uint16_t rocketWidth  = 32;
constexpr uint16_t rocketHeight = 48;

constexpr uint24_t radar = 0x001514;
constexpr uint16_t radarWidth  = 40;
constexpr uint16_t radarHeight = 64;

constexpr uint24_t fungus = 0x001658;
constexpr uint16_t fungusWidth  = 24;
constexpr uint16_t fungusHeight = 32;

constexpr uint24_t waggon = 0x0016BC;
constexpr uint16_t waggonWidth  = 32;
constexpr uint16_t waggonHeight = 40;

constexpr uint24_t ship_laser = 0x001760;
constexpr uint16_t ship_laser_width  = 8;
constexpr uint16_t ship_laser_height = 128;
constexpr uint8_t  ship_laser_frames = 8;

constexpr uint24_t piston_pic = 0x001B64;
constexpr uint16_t piston_pic_width  = 24;
constexpr uint16_t piston_pic_height = 32;
constexpr uint8_t  piston_pic_frames = 10;

constexpr uint24_t enemy_bubble_pic = 0x001F28;
constexpr uint16_t enemy_bubble_pic_width  = 16;
constexpr uint16_t enemy_bubble_pic_height = 16;
constexpr uint8_t  enemy_bubble_pic_frames = 3;

constexpr uint24_t enemy_interceptor_pic = 0x001F8C;
constexpr uint16_t enemy_interceptor_pic_width  = 16;
constexpr uint16_t enemy_interceptor_pic_height = 16;
constexpr uint8_t  enemy_interceptor_pic_frames = 3;

constexpr uint24_t enemy_jellyfish_pic = 0x001FF0;
constexpr uint16_t enemy_jellyfish_pic_width  = 16;
constexpr uint16_t enemy_jellyfish_pic_height = 16;
constexpr uint8_t  enemy_jellyfish_pic_frames = 3;

constexpr uint24_t enemy_louse_pic = 0x002054;
constexpr uint16_t enemy_louse_pic_width  = 16;
constexpr uint16_t enemy_louse_pic_height = 16;
constexpr uint8_t  enemy_louse_pic_frames = 3;

constexpr uint24_t turret_pic = 0x0020B8;
constexpr uint16_t turret_pic_width  = 48;
constexpr uint16_t turret_pic_height = 40;

constexpr uint24_t turret_bullet_pic = 0x0021AC;
constexpr uint16_t turret_bullet_pic_width  = 2;
constexpr uint16_t turret_bullet_pic_height = 2;

constexpr uint24_t double_launcher_pic = 0x0021B2;
constexpr uint16_t double_launcher_pic_width  = 32;
constexpr uint16_t double_launcher_pic_height = 24;

constexpr uint24_t double_launcher_bullet_pic = 0x002216;
constexpr uint16_t double_launcher_bullet_pic_width  = 8;
constexpr uint16_t double_launcher_bullet_pic_height = 8;

constexpr uint24_t combined_launcher_top_pic = 0x002222;
constexpr uint16_t combined_launcher_top_pic_width  = 56;
constexpr uint16_t combined_launcher_top_pic_height = 16;

constexpr uint24_t combined_launcher_bottom_pic = 0x002296;
constexpr uint16_t combined_launcher_bottom_pic_width  = 56;
constexpr uint16_t combined_launcher_bottom_pic_height = 16;

constexpr uint24_t incubator_pic = 0x00230A;
constexpr uint16_t incubator_pic_width  = 32;
constexpr uint16_t incubator_pic_height = 48;

constexpr uint24_t missile_tower_pic = 0x0023CE;
constexpr uint16_t missile_tower_pic_width  = 32;
constexpr uint16_t missile_tower_pic_height = 40;

constexpr uint24_t missile_guidance_pic = 0x002472;
constexpr uint16_t missile_guidance_pic_width  = 32;
constexpr uint16_t missile_guidance_pic_height = 32;

constexpr uint24_t missile_pic = 0x0024F6;
constexpr uint16_t missile_pic_width  = 16;
constexpr uint16_t missile_pic_height = 16;
constexpr uint8_t  missile_pic_frames = 2;

constexpr uint24_t mine_pic = 0x00253A;
constexpr uint16_t mine_pic_width  = 16;
constexpr uint16_t mine_pic_height = 8;

constexpr uint24_t teleport_pic = 0x00254E;
constexpr uint16_t teleport_pic_width  = 32;
constexpr uint16_t teleport_pic_height = 48;
constexpr uint8_t  teleport_pic_frames = 8;

constexpr uint24_t ship_fire = 0x002B52;
constexpr uint16_t ship_fire_width  = 8;
constexpr uint16_t ship_fire_height = 16;
constexpr uint8_t  ship_fire_frames = 3;

constexpr uint24_t enemy_type_levels = 0x002B86;
constexpr uint24_t Levels_bg_1 = 0x002C03;
constexpr uint16_t Levels_bg_1_width  = 256;
constexpr uint16_t Levels_bg_1_height = 176;
constexpr uint8_t  Levels_bg_1_frames = 25;

constexpr uint24_t Levels_bg_2 = 0x025207;
constexpr uint16_t Levels_bg_2_width  = 256;
constexpr uint16_t Levels_bg_2_height = 176;
constexpr uint8_t  Levels_bg_2_frames = 25;

constexpr uint24_t Levels_bg_3 = 0x04780B;
constexpr uint16_t Levels_bg_3_width  = 256;
constexpr uint16_t Levels_bg_3_height = 176;
constexpr uint8_t  Levels_bg_3_frames = 25;

constexpr uint24_t Levels_bg_4 = 0x069E0F;
constexpr uint16_t Levels_bg_4_width  = 256;
constexpr uint16_t Levels_bg_4_height = 176;
constexpr uint8_t  Levels_bg_4_frames = 25;

constexpr uint24_t Levels_bg_5 = 0x08C413;
constexpr uint16_t Levels_bg_5_width  = 256;
constexpr uint16_t Levels_bg_5_height = 176;
constexpr uint8_t  Levels_bg_5_frames = 25;

constexpr uint24_t Level_0 = 0x0AEA17;
constexpr uint24_t Level_1 = 0x0AECD7;
constexpr uint24_t Level_2 = 0x0AEF97;
constexpr uint24_t Level_3 = 0x0AF257;
constexpr uint24_t Level_4 = 0x0AF517;
constexpr uint24_t Level_5 = 0x0AF7D7;
constexpr uint24_t Level_6 = 0x0AFA97;
constexpr uint24_t Level_7 = 0x0AFD57;
constexpr uint24_t Level_8 = 0x0B0017;
constexpr uint24_t Level_9 = 0x0B02D7;
constexpr uint24_t Level_10 = 0x0B0597;
constexpr uint24_t Level_11 = 0x0B0857;
constexpr uint24_t Level_12 = 0x0B0B17;
constexpr uint24_t Level_13 = 0x0B0DD7;
constexpr uint24_t Level_14 = 0x0B1097;
constexpr uint24_t Level_15 = 0x0B1357;
constexpr uint24_t Level_16 = 0x0B1617;
constexpr uint24_t Level_17 = 0x0B18D7;
constexpr uint24_t Level_18 = 0x0B1B97;
constexpr uint24_t Level_19 = 0x0B1E57;
constexpr uint24_t Level_20 = 0x0B2117;
constexpr uint24_t Level_21 = 0x0B23D7;
constexpr uint24_t Level_22 = 0x0B2697;
constexpr uint24_t Level_23 = 0x0B2957;
constexpr uint24_t Level_24 = 0x0B2C17;
constexpr uint24_t Level_25 = 0x0B2ED7;
constexpr uint24_t Level_26 = 0x0B3197;
constexpr uint24_t Level_27 = 0x0B3457;
constexpr uint24_t Level_28 = 0x0B3717;
constexpr uint24_t Level_29 = 0x0B39D7;
constexpr uint24_t Level_30 = 0x0B3C97;
constexpr uint24_t Level_31 = 0x0B3F57;
constexpr uint24_t Level_32 = 0x0B4217;
constexpr uint24_t Level_33 = 0x0B44D7;
constexpr uint24_t Level_34 = 0x0B4797;
constexpr uint24_t Level_35 = 0x0B4A57;
constexpr uint24_t Level_36 = 0x0B4D17;
constexpr uint24_t Level_37 = 0x0B4FD7;
constexpr uint24_t Level_38 = 0x0B5297;
constexpr uint24_t Level_39 = 0x0B5557;
constexpr uint24_t Level_40 = 0x0B5817;
constexpr uint24_t Level_41 = 0x0B5AD7;
constexpr uint24_t Level_42 = 0x0B5D97;
constexpr uint24_t Level_43 = 0x0B6057;
constexpr uint24_t Level_44 = 0x0B6318;
constexpr uint24_t Level_45 = 0x0B65D8;
constexpr uint24_t Level_46 = 0x0B6898;
constexpr uint24_t Level_47 = 0x0B6B58;
constexpr uint24_t Level_48 = 0x0B6E18;
constexpr uint24_t Level_49 = 0x0B70D8;
constexpr uint24_t Level_50 = 0x0B7398;
constexpr uint24_t Level_51 = 0x0B7658;
constexpr uint24_t Level_52 = 0x0B7918;
constexpr uint24_t Level_53 = 0x0B7BD8;
constexpr uint24_t Level_54 = 0x0B7E98;
constexpr uint24_t Level_55 = 0x0B8158;
constexpr uint24_t Level_56 = 0x0B8418;
constexpr uint24_t Level_57 = 0x0B86D8;
constexpr uint24_t Level_58 = 0x0B8998;
constexpr uint24_t Level_59 = 0x0B8C58;
constexpr uint24_t Level_60 = 0x0B8F18;
constexpr uint24_t Level_61 = 0x0B91D8;
constexpr uint24_t Level_62 = 0x0B9498;
constexpr uint24_t Level_63 = 0x0B9758;
constexpr uint24_t Level_64 = 0x0B9A18;
constexpr uint24_t Level_65 = 0x0B9CD8;
constexpr uint24_t Level_66 = 0x0B9F98;
constexpr uint24_t Level_67 = 0x0BA258;
constexpr uint24_t Level_68 = 0x0BA518;
constexpr uint24_t Level_69 = 0x0BA7D8;
constexpr uint24_t Level_70 = 0x0BAA98;
constexpr uint24_t Level_71 = 0x0BAD58;
constexpr uint24_t Level_72 = 0x0BB018;
constexpr uint24_t Level_73 = 0x0BB2D8;
constexpr uint24_t Level_74 = 0x0BB598;
constexpr uint24_t Level_75 = 0x0BB858;
constexpr uint24_t Level_76 = 0x0BBB18;
constexpr uint24_t Level_77 = 0x0BBDD8;
constexpr uint24_t Level_78 = 0x0BC098;
constexpr uint24_t Level_79 = 0x0BC358;
constexpr uint24_t Level_80 = 0x0BC618;
constexpr uint24_t Level_81 = 0x0BC8D8;
constexpr uint24_t Level_82 = 0x0BCB98;
constexpr uint24_t Level_83 = 0x0BCE58;
constexpr uint24_t Level_84 = 0x0BD118;
constexpr uint24_t Level_85 = 0x0BD3D8;
constexpr uint24_t Level_86 = 0x0BD698;
constexpr uint24_t Level_87 = 0x0BD958;
constexpr uint24_t Level_88 = 0x0BDC18;
constexpr uint24_t Level_89 = 0x0BDED8;
constexpr uint24_t Level_90 = 0x0BE198;
constexpr uint24_t Level_91 = 0x0BE458;
constexpr uint24_t Level_92 = 0x0BE718;
constexpr uint24_t Level_93 = 0x0BE9D8;
constexpr uint24_t Level_94 = 0x0BEC98;
constexpr uint24_t Level_95 = 0x0BEF58;
constexpr uint24_t Level_96 = 0x0BF218;
constexpr uint24_t Level_97 = 0x0BF4D8;
constexpr uint24_t Level_98 = 0x0BF798;
constexpr uint24_t Level_99 = 0x0BFA58;
constexpr uint24_t Level_100 = 0x0BFD18;
constexpr uint24_t Level_101 = 0x0BFFD8;
constexpr uint24_t Level_102 = 0x0C0298;
constexpr uint24_t Level_103 = 0x0C0558;
constexpr uint24_t Level_104 = 0x0C0818;
constexpr uint24_t Level_105 = 0x0C0AD8;
constexpr uint24_t Level_106 = 0x0C0D98;
constexpr uint24_t Level_107 = 0x0C1058;
constexpr uint24_t Level_108 = 0x0C1318;
constexpr uint24_t Level_109 = 0x0C15D8;
constexpr uint24_t Level_110 = 0x0C1898;
constexpr uint24_t Level_111 = 0x0C1B58;
constexpr uint24_t Level_112 = 0x0C1E18;
constexpr uint24_t Level_113 = 0x0C20D8;
constexpr uint24_t Level_114 = 0x0C2398;
constexpr uint24_t Level_115 = 0x0C2658;
constexpr uint24_t Level_116 = 0x0C2918;
constexpr uint24_t Level_117 = 0x0C2BD8;
constexpr uint24_t Level_118 = 0x0C2E98;
constexpr uint24_t Level_119 = 0x0C3158;
constexpr uint24_t Level_120 = 0x0C3418;
constexpr uint24_t Level_121 = 0x0C36D8;
constexpr uint24_t Level_122 = 0x0C3998;
constexpr uint24_t Level_123 = 0x0C3C58;
constexpr uint24_t Level_124 = 0x0C3F18;
